tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
brew "asdf"
brew "coreutils"
brew "gh"
brew "git"
brew "imagemagick"
brew "mas"
brew "mysql"
brew "openssl@3"
brew "php"
brew "poppler"
brew "postgresql@14"
brew "rcm"
brew "reattach-to-user-namespace"
brew "redis"
brew "the_silver_searcher"
brew "tmux"
brew "universal-ctags", args: ["HEAD"]
brew "vim"
brew "watchman"
brew "yarn"
brew "zsh"
brew "thoughtbot/formulae/parity"
cask "1password"
cask "1password/tap/1password-cli"
cask "alfred"
cask "cleanmymac"
cask "dash"
cask "dropbox"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "microsoft-teams"
cask "rectangle"
cask "spotify"
cask "tuple"
cask "whatsapp"
cask "zoom"
mas "Bear", id: 1091189122
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
