version: '2.1'

orbs:
  shellcheck: circleci/shellcheck@3.1.2

jobs:
  shellcheck/check:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - shellcheck/install
      - run:
          command: shellcheck **/*.sh {aliases,laptop,zshrc}.local
          name: Run Shellcheck command

workflows:
  build:
    jobs:
      - shellcheck/check
